#!/bin/bash

# Check if autodoor is running or not
if [ -f /home/pi/Autodoor/run/autodoor.pid ]
then
    ps -p `cat /home/pi/Autodoor/run/autodoor.pid` > /dev/null 2>&1
    if [ $? == 1 ]
    then
		echo "############################**Run-Time**##################################"
		date
		echo "Autodoor is not running starting it now."
		tmux kill-session -t 0 > /dev/null 2>&1
        tmux new -d /home/pi/Autodoor/autodoor
    fi
else
	echo "############################**Run-Time**##################################"
	date
	echo "Autodoor is not running starting it now."
	tmux kill-session -t 0 > /dev/null 2>&1
    tmux new -d /home/pi/Autodoor/autodoor
fi

