#!/bin/bash
######################################################################################################
# Program	: gitpush
# Author	: Chauncey Yan
# Functions	:
# Revision	: 0.1
# Mod date	: Oct 21 2014
# Updates	:
# Issues	:
######################################################################################################
# Main		:
# Issues	:
######################################################################################################

if [[ -z $@ ]];then
	echo Error: missing commit message.
	exit
fi 

git st
git add .
git commit -m ""$@""
git push -u origin


