#!/bin/bash

INSTALL_DIR=`pwd`
LOG_DIR='/var/log'
RUN_DIR='/var/run'
USERNAME='pi'

if [ "$(id -u)" != "0" ]; then
echo "This script must be run as root" 1>&2
exit 1
fi

if [ ! -d "$LOG_DIR" ]
then
	echo "Creating log directory"
	mkdir -p "$LOG_DIR"
	chown -R "$USERNAME":"$USERNAME" "$LOG_DIR"
else
	echo "log directory already exists"
fi

if [ ! -d "$RUN_DIR" ]
then
	echo "Creating run directory"
	mkdir -p "$RUN_DIR"
	chown -R "$USERNAME":"$USERNAME" "$RUN_DIR"
else
	echo "Run directory already exists"
fi


echo "*/2 * * * *	$USERNAME	$INSTALL_DIR/door_runtime >> $LOG_DIR/autodoor.log 2>&1" >> /etc/crontab

echo "*/5 * * * *	root	$INSTALL_DIR/net_checker >> $LOG_DIR/autodoor.log 2>&1" >> /etc/crontab

