#!/bin/bash

INSTALL_DIR='/home/pi/Autodoor'
LOG_DIR='/home/pi/Autodoor/log'
RUN_DIR='/home/pi/Autodoor/run'
USERNAME='pi'

if [ ! -d "$LOG_DIR" ]
then
	echo "Creating log directory"
	sudo mkdir -p "$LOG_DIR"
	sudo chown -R "$USERNAME":"$USERNAME" "$LOG_DIR"
else
	echo "log directory already exists"
fi

if [ ! -d "$RUN_DIR" ]
then
	echo "Creating run directory"
	sudo mkdir -p "$RUN_DIR"
	sudo chown -R "$USERNAME":"$USERNAME" "$RUN_DIR"
else
	echo "Run directory already exists"
fi


sudo echo "*/2 * * * *	$USERNAME	$INSTALL_DIR/door_runtime >> $LOG_DIR/autodoor.log 2>&1" >> /etc/crontab

sudo echo "*/5 * * * *	root	$INSTALL_DIR/net_checker >> $LOG_DIR/autodoor.log 2>&1" >> /etc/crontab

