#!/bin/bash
# Check if connected to the internet
while [ 1 ];do
ping -c 2 -w 2 google.com > /dev/null 2>&1 
if [ $? == 1 ]
then
	ping -c 2 -w 2 google.com > /dev/null 2>&1 
	if [ $? == 1 ]
	then
		echo "##############################**Net-Checker**#############################"
		date
		echo "Not connected to the Interwebs, Rebooting"
	    reboot
	fi
fi
sleep 2m
done
