#! /usr/bin/python
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)

GPIO.setup(23, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)

GPIO.setup(24, GPIO.IN, pull_up_down = GPIO.PUD_UP)
running = 0
while True:
    if(GPIO.input(23) ==1 and running != 1):
        print 'Button 1 pressed'
        running = 1
    if(GPIO.input(23) == 0 and running != 0):
        running = 0
GPIO.cleanup()
